vendas_vendedores={}
vendas_vendedores["Joao"]=100
print(vendas_vendedores)
vendas_vendedores.update({"Lira":50,"Nathalie":80})
print(vendas_vendedores)
vendas_vendedores["Joao"]=70
print(vendas_vendedores)
vendas_vendedores.update({"Lira":67,"Nathalie":12})
print(vendas_vendedores)