arquivo=open("C:/Users/felipe_santos154/Documents/txt/TSPS.txt","w")
arquivo.write("Escrevendo um arquivo\n")
arquivo.write("Homer Simpson\n")
arquivo.write("Marge Simpson\n")
arquivo.write("Maggie Simpson\n")
arquivo.write("Bart Simpson\n")
arquivo.write("Lisa Simpson\n")
arquivo.close()
print("Fim programa")