arquivo=open("C:/Users/felipe_santos154/Documents/txt/GOT.txt","w")
arquivo.write("Escrevendo um arquivo\n")
arquivo.write("John Snow\n")
arquivo.write("Arya Stark\n")
arquivo.write("Sansa Stark\n")
arquivo.write("Bran Stark\n")
arquivo.close()
print("Fim programa")